In [1]:
import torch
import numpy as np

In [ ]:
#from explicit data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
#from numpy array
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [11]:
x_ones = torch.ones_like(x_data) #override to fill with ones
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float) #override datatype
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9701, 0.3286],
        [0.3899, 0.8889]])


In [18]:
tensor = torch.rand(3,4) #set dimensions
print(tensor)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.7402, 0.8877, 0.1799, 0.5875],
        [0.8720, 0.7477, 0.9706, 0.9827],
        [0.4022, 0.6819, 0.6121, 0.0438]])
torch.Size([3, 4])
torch.float32
cpu


In [21]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(torch.accelerator.current_accelerator())

cuda


In [ ]:
tensor = torch.ones(4,4)
print(tensor[0])
print(tensor[:,0]) #all rows in column 0
print(tensor[...,-1]) #extract last column
tensor[:,1]=0 #all rows in column 1, set to 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
tensor = torch.ones(4,4)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)


In [ ]:
#convert to numerical value

agg = tensor.sum()
agg_item = agg.item()